# Версия формата Docker Compose.
version: '3'

# Описание сервисов (контейнеров), которые будут запущены.
services:

  # Контейнер Redis для работы с кэшем и хранения данных.
  redis:
    image: redis
    ports:
      - '6379:6379'

  # Контейнер PostgreSQL для хранения данных в базе данных.
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Контейнер для приложения.
  app:
    build: .
    tty: true
    command: sh -c "python manage.py migrate &&
         python manage.py runserver 0.0.0.0:8000"

    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  # Контейнер для запуска заданий Celery.
  celery:
    build: .
    tty: true
    command: celery -A config worker -l info -P gevent
    depends_on:
      - redis
      - app

  # Контейнер для запуска Celery-beat.
  celery-beat:
    build: .
    tty: true
    command: celery -A config beat -l info -S django
    depends_on:
      - redis
      - app
      - celery

volumes:
  pg_data:
